GET http://localhost:8080/api/auth/test
Accept: application/json

###
POST http://localhost:8080/api/auth/authenticate
Content-Type: application/json
Accept: application/json

{
  "email": "David1@outlook.com",
  "password": "David1"
}

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json
Accept: application/json


{
  "first_name": "David5",
  "lastname": "David5",
  "email": "David5@outlook.com",
  "password": "David5"
}

###
GET http://localhost:8080/api/demo
Accept: application/json
Cookie: JWT=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwic3ViIjoiMTAiLCJpYXQiOjE3Mjk1MTQ0MDgsImV4cCI6MTcyOTUxODAwOH0.6AsAnRGME3CyWjBAGoGJ1fJgwoYmAyefOlWTVE4MF4I

###
GET http://localhost:8080/api/demo
Accept: application/json



