GET http://localhost:8080/api/auth/test
Accept: application/json

###
POST http://localhost:8080/api/auth/authenticate
Content-Type: application/json
Accept: application/json

{
  "email": "David1@outlook.com",
  "password": "David1"
}

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json
Accept: application/json


{
  "first_name": "David7",
  "lastname": "David7",
  "email": "David7@outlook.com",
  "password": "David7"
}

###
GET http://localhost:8080/api/demo
Accept: application/json
Cookie: JWT=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiMTAiLCJpYXQiOjE3Mjk1MTczODIsImV4cCI6MTcyOTUyMDk4Mn0.UHn-8FgtHszDbZpj6RGgUTPABKXgYCIMg15hPDA4CTs

###
GET http://localhost:8080/api/demo
Accept: application/json



