name: Docker Image Build and Push

on:
  workflow_run:
    workflows: ["CI Fontys_solutions"]  # The name main CI workflow
    types:
      - completed
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api:
          - User
          - userfrontend
        
    steps:    
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build Docker Image based on matrix 'api'
      - name: Build Docker image for ${{ matrix.api }}
        run: |
          docker build ./${{ matrix.api }} -t davidsteile/${{ matrix.api.toLowerCase() }}:latest

          
      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push davidsteile/${{ matrix.api.toLowerCase() }}:latest
