name: CI for Fontys_solutions userapi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api:
          - User

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Clean, compile, and run tests
      run: mvn -B clean verify -Dtest=com.api.user.service.* --file "${{ matrix.api }}/pom.xml"

    - name: Build application
      run: mvn -B clean package --file "${{ matrix.api }}/pom.xml"
