name: CI for Fontys_solutions userapi

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LANGUAGE: "java,javascript,typescript,xml"
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true
          VALIDATE_GITLEAKS: true
          
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api:
          - User

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Clean, compile, and run tests
      run: mvn -B clean verify --file "${{ matrix.api }}/pom.xml"
      
    - name: Build application
      run: mvn -B clean package --file "${{ matrix.api }}/pom.xml"
