name: CI/CD for Fontys Solutions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./User

      - name: Run unit tests for User API
        run: mvn -Dtest='com.api.user.service.**' test  # Specify 'test' goal here
        working-directory: ./User
      
      - name: Upload test results for User API
        uses: actions/upload-artifact@v4
        with:
          name: test-results-userapi
          path: /target/surefire-reports  # Adjusted path
