name: CI for Fontys_solutions userapi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package
      working-directory: User

    # Dependency graph update with default working directory
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        working-directory: User

      
    - name: Run tests service
      run: mvn -Dtest=com.api.user.service.* test
      working-directory: User
      
    - name: Archive Surefire reports unittests
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: |
          **/target/surefire-reports/*.xml
          **/target/surefire-reports/*.txt
        working-directory: User

