name: CI for Fontys_solutions userapi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 22 
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn -Dtest=com.api.user.service.* test

    - name: Archive Surefire reports unittests
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: |
          **/target/surefire-reports/*.xml
          **/target/surefire-reports/*.txt

