name: CI for Fontys_solutions userapi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package
      working-directory: User
      
    - name: Run tests service
      run: mvn -Dtest=com.api.user.service.* test
      working-directory: User
